{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "worldcup-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "worldcup-app.labels" . | nindent 4 }}
    release: {{ .Values.monitoring.prometheusRelease }}
spec:
  selector:
    matchLabels:
      {{- include "worldcup-app.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
